### ISSUE TITLE
Crash on startup 1.18.1

### ISSUE THREAD

**Issue by donoya** [boblovespi/FactoryAutomation#13]
[latest.log](https://github.com/boblovespi/FactoryAutomation/files/7804855/latest.log)
The only mods besides this that are being used are forge 39.0.8 for minecraft 1.18.1, patchouli version 63, and JEI. version 9.1.2.54.

**Comment by donoya** [comment]
It also happens on forge 39.0.10.

**Comment by boblovespi** [comment]
you need geckolib as well

**Comment by donoya** [comment]
Thank you. That solved it. Maybe update the description so people are aware of that.
