### ISSUE TITLE
Game crashes on start

### ISSUE THREAD

**Issue by SpeakerHornet** [boblovespi/FactoryAutomation#8]
**Describe the bug**
Game crashes on start.

**Link to complete log**
https://paste.ee/p/e5oqk

**To Reproduce**
Start a game with following Desktop information.

**Desktop (please complete the following information):**
 - Forge version: [e.g. 14.23.5.2796]
 - Factory Automation version: [e.g. v0.2.1]
 - Other mods [No other mods]

**Comment by boblovespi** [comment]
do you have patchouli installed? patchouli is a hard dependency right now

**Comment by SpeakerHornet** [comment]
oh yea, sorry i forgot about it

**Comment by boblovespi** [comment]
i'll try to remove the dependency on patchouli in the next update
