### ISSUE TITLE
Factory Automation causes cascading world gen.

### ISSUE THREAD

**Issue by SpeakerHornet** [boblovespi/FactoryAutomation#9]
**Describe the bug**
Title. It does it the whole time.

**Link to complete log**
https://paste.ee/p/mIo10

**Desktop (please complete the following information):**
 - Forge version: [e.g. 14.23.5.2803]
 - Factory Automation version: 0.2.1

Tell me if you need any more details.

**Comment by boblovespi** [comment]
closing because new minecraft version and it should no longer happen
